### PR TITLE
Add SimpleX as Signal alternative

### PR DESCRIPTION
**Pull request by sshine**
After confirmation in #129, and after the release of the SimpleX mobile clients,
adding SimpleX as a real Signal alternative seems like a good idea. There are
mostly good things to say, in my opinion (I'm not affiliated), but I've still tried to
remain neutral.

### CODE REVIEW

**Comment by dessalines** [comment]
Seems good to me, thanks!

**Comment by Gioele-Bencivenga** [comment]
I'd love to see a Session paragraph too (https://github.com/oxen-io/session-desktop)
Session was initially a Signal fork but they removed phone numbers along with many other changes
Not affiliated

**Comment by dessalines** [comment]
Probably not going to add anything that isn't easily self-hostable.

**Comment by Gioele-Bencivenga** [comment]
Fair and understandable

**Pull request merged**
